name: Build C# Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Restore dependencies
      run: dotnet restore Sharpmssqluser.sln

    - name: Build project
      run: dotnet build Sharpmssqluser.sln --configuration Release --no-restore
	  
    - name: Build with MSBuild (.NET Framework)
      run: msbuild Sharpmssqluser.csproj /p:Configuration=Release /p:Platform="Any CPU"
	  
    - name: Copy output to publish folder
      run: |
        mkdir publish
        copy .\bin\Release\* .\publish\
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: .\publish\*
         tag: ${{ github.ref }}
         overwrite: true
         file_glob: true
         draft: false 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sharpmssqluser-publish
        path: ./publish
